# Generated by Django 4.2.1 on 2023-05-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=6)),
                ('original_url', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
