# Generated by Django 4.2.1 on 2023-05-26 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='slug',
        ),
        migrations.AddField(
            model_name='url',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 9, 6, 52, 158956)),
        ),
        migrations.AddField(
            model_name='url',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='url',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
