# Generated by Django 4.2.1 on 2023-05-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_alter_url_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='short_url',
        ),
    ]
