# Generated by Django 4.2.1 on 2023-05-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_remove_url_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='short_url',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
